Bruke Debug-logo
appKom/infoskjerm pull request #190
Opened 2024-10-21 14:07 UTC by jorgengaldal

2024-10-21 14:09 UTC, julian-ao commented
Er ikke sånn superfan av det designet. Jeg hadde gjort den endel mindre, og kanskje samme farge som teksten.
![image](https://github.com/user-attachments/assets/ceb7ab22-103c-4f3f-b35a-c3eb229cf396)

Evt bytte ut online-logoen i QR-koden med edbug logoen også?

2024-10-21 14:10 UTC, julian-ao requested changes
Er ikke sånn superfan av det designet. Jeg hadde gjort den endel mindre, og kanskje samme farge som teksten.
![image](https://github.com/user-attachments/assets/ceb7ab22-103c-4f3f-b35a-c3eb229cf396)

Evt bytte ut online-logoen i QR-koden med edbug logoen også?

2024-10-21 14:24 UTC, jorgengaldal commented
Tror kanskje designet er litt for detaljert til at det passer å ha det i midten av QR-koden?

2024-10-21 14:25 UTC, jorgengaldal commented
![image](https://github.com/user-attachments/assets/21687483-a8bf-4054-8447-1136a6c8c1d4)
![image](https://github.com/user-attachments/assets/0968aa10-e452-40ea-8c26-01de5ae7a2a7)

2024-10-22 11:26 UTC, julian-ao approved these changes

2024-10-24 12:58 UTC, merged